### ISSUE TITLE
关于夜间模式不起作用 

### ISSUE THREAD

**Issue by chenjingzhang** [z-chu/FriendBook#24]
我设置了夜间模式 可是只有在点击返回键 重新进入应用后  夜间模式才生效。 是将 所有的activity都继承baseactivit. 在baseactivity中重写了initTheme(). 这样做 对吗

**Comment by z-chu** [comment]
只要调用`AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES)`，再把已经存在的Activity 调用`recreate`重新创建就可以实现切换。
具体你可以参考 [这篇文章](https://www.jianshu.com/p/abcd4574b8c3)

**Comment by chenjingzhang** [comment]
再把已经存在的activity.  好多的activity 都需要调用recreate吗

**Comment by z-chu** [comment]
是的

**Comment by z-chu** [comment]
所以建议把夜间模式切换放在根Activity,这样就只要重新创建一个activity

**Comment by chenjingzhang** [comment]
我让所有的activity. 都继承base activity  在base activity 中的onCreate里面写了。    private void initTheme() {
        //设置该app的主题根据时间不同显示
        if (SettingYeJianModel.isNightMode()) {
            AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES);
        } else {
            AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_NO);
        }
        recreate();
    }

结果进去应用 全白的

**Comment by chenjingzhang** [comment]
可以帮助我分析下 哪里错了吗

**Comment by z-chu** [comment]
在切换的时候才去调用recreate...，你这样会无限重建的

**Comment by chenjingzhang** [comment]
如果 initTheme()中去掉 recreate .我切换完后 不会立刻生效。只有重启 应用 才变成夜间模式

**Comment by chenjingzhang** [comment]
swNightMode.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {
            @Override
            public void onCheckedChanged(CompoundButton compoundButton, boolean b) {
                if (!b) {

                    getDelegate()
                            .setLocalNightMode(AppCompatDelegate.MODE_NIGHT_NO);
                    SettingYeJianModel.setNightMode(false);
                    swNightMode.setChecked(false);
                } else {
                    getDelegate()
                            .setLocalNightMode(AppCompatDelegate.MODE_NIGHT_YES);
                    SettingYeJianModel.setNightMode(true);
                    swNightMode.setChecked(true);
                }
                recreate();
            }
        }); 这个是我切换的代码

**Comment by chenjingzhang** [comment]
您好 有时间可以帮我看下吗
