### ISSUE TITLE
求服务器端代码

### ISSUE THREAD

**Issue by niupuyue** [z-chu/FriendBook#25]
兄die，代码写的很好，正在学习中，其中的图书内容展示给了我很多启发，谢谢，开源万岁！
不过我想问一下，能不能求到服务器端的代码呢？如果有就最好了，感激不尽！

**Comment by z-chu** [comment]
服务端代码不是我在维护哦，开源估计也是很早之前的代码了。你可以看看 [torch05/FriendBook](https://github.com/torch05/FriendBook)

**Comment by niupuyue** [comment]
OK，谢啦兄die
